#!/bin/sh -e

if ! getent group skeleton > /dev/null 2>&1 ; then
addgroup --system --quiet skeleton
fi

if ! getent passwd skeleton > /dev/null 2>&1 ; then
adduser --quiet \
--system --disabled-login --ingroup skeleton \
--home /var/run/skeleton/ --no-create-home \
skeleton
fi

chown skeleton:skeleton /var/log/py-daemon-skeleton -R

# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
    pycompile -p skeleton 
fi

# End automatically added section
# Automatically added by dh_installinit
if [ -x "/etc/init.d/py-daemon-skeleton" ]; then
    update-rc.d py-daemon-skeleton defaults >/dev/null
    invoke-rc.d py-daemon-skeleton start || exit $?
fi
# End automatically added section


exit 0
