#!/bin/sh -e

if ! getent group puppetdiff > /dev/null 2>&1 ; then
addgroup --system --quiet puppetdiff
fi

if ! getent passwd puppetdiff > /dev/null 2>&1 ; then
adduser --quiet \
--system --disabled-login --ingroup puppetdiff \
--home /var/run/puppetdiff/ --no-create-home \
puppetdiff
fi

chown puppetdiff:puppetdiff /var/log/puppetdiff -R

# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
    pycompile -p puppetdiff 
fi

# End automatically added section
# Automatically added by dh_installinit
if [ -x "/etc/init.d/puppetdiff" ]; then
    update-rc.d puppetdiff defaults >/dev/null
    invoke-rc.d puppetdiff start || exit $?
fi
# End automatically added section


exit 0
